name: CI/CD 

on:
  push:
    branches: [ "develop" ]

env:
  ECS_TASK_DEFINITION: task-definition.json 
  CONTAINER_NAME: kuizu-users-microservice
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  ECS_SERVICE: ${{ secrets.ECS_SERVICE }}
  ECS_CLUSTER: ${{ secrets.ECS_CLUSTER }}

permissions:
  contents: read
jobs:
  build:
    name: Build 🔨
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.12.1
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
  test:
    needs: [build]
    name: Test 📝
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm test
  deploy:
    needs: [build, test]
    name: Deploy 🚀
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Google Chat Notification
      uses: Co-qn/google-chat-notification@releases/v1
      with:
        name: Build Starting
        url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
        status: ${{ job.status }}
      if: always()
      
    - name: Create ZIP deployment package
      run: zip -r deploy_package.zip ./

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Upload package to S3 bucket
      run: aws s3 cp deploy_package.zip s3://kuizu-app-deploy/
    
    - name: Create new ElasticBeanstalk Application Version
      run: |
        aws elasticbeanstalk create-application-version \
        --application-name Kuizu-App \
        --source-bundle S3Bucket="kuizu-app-deploy",S3Key="deploy_package.zip" \
        --version-label "ver-${{ github.sha }}" \
        --description "commit-sha-${{ github.sha }}"

    - name: Deploy new ElasticBeanstalk Application Version
      run: aws elasticbeanstalk update-environment --environment-name Kuizuapp-user --version-label "ver-${{ github.sha }}"
        
    - name: Google Chat Notification
      uses: Co-qn/google-chat-notification@releases/v1
      with:
        name: Build ended
        url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
        status: ${{ job.status }}
      if: always()
